### ISSUE TITLE
Opening .plantuml file keeps loading

### ISSUE THREAD

**Issue by ShenGuangYang** [emako/QuickLook.Plugin.PlantUMLViewer#1]
I installed the java8 environment and opened the .plantuml file and it kept loading

![image](https://github.com/user-attachments/assets/c1dcf30e-4c8d-4089-a5a9-edce4da6b556)

![image](https://github.com/user-attachments/assets/49070486-fbb8-49d8-80bd-1921d083aee4)

![image](https://github.com/user-attachments/assets/d50ca3f6-093d-43a1-9612-b1cc69ea9d9a)

**Comment by ShenGuangYang** [comment]
Further investigation shows that the plug-in was not installed properly when it was installed.
![image](https://github.com/user-attachments/assets/f9a4e7ed-b106-4678-923a-665e092ae308)

**Comment by emako** [comment]
Fixed in v1.1.0
https://github.com/emako/QuickLook.Plugin.PlantUMLViewer/releases/tag/v1.1.0
